## Usage

In [1]:
from IPython.display import display
import pandas as pd

### TSETMC Website API
Fetches all Bourse and FaraBours data (suitable for screening the total market).

In [2]:
from tseopt import get_all_options_data

entire_option_market_data = get_all_options_data()

display(entire_option_market_data.head(5))
print(entire_option_market_data.iloc[0])

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,42832,42832,44616,20260620,20260916,46000,65,...,303,40,اختيارخ اهرم-46000-1405/06/25,ضهرم6046,6001,100,6800,64,2865,call
1,1000,778253364357513,وبملت,1196,1196,1232,20260602,20260811,1000,29,...,75080,406,اختيارخ وبملت-1000-1405/05/20,ضملت5029,227,1500,235,5,288451,call
2,1000,778253364357513,وبملت,1196,1196,1232,20260602,20260811,1600,29,...,25372,78,اختيارخ وبملت-1600-1405/05/20,ضملت5035,14,1368,15,1000,116802,call
3,1000,65883838195688438,خودرو,544,548,559,20260701,20260930,400,79,...,54128,258,اختيارخ خودرو-400-1405/07/08,ضخود7129,183,51,186,37,128215,call
4,1000,67455383896188985,جوانه كوچك,18487,18482,19053,20260607,20260715,20000,2,...,1242,5,اختيارخ جوانه.ك-20000-05/04/24,ضجوا4007,4,444,82,124,2431,call

contract_size                                        1000
ua_tse_code                             17914401175772326
ua_ticker                                            اهرم
ua_close_price                                      42832
ua_last_price                                       42832
ua_yesterday_price                                  44616
begin_date                                       20260620
end_date                                         20260916
strike_price                                        46000
days_to_maturity                                       65
tse_code                                25894644635630608
last_price                                           6300
open_positions                                       2865
close_price                                          6215
yesterday_price                                      5868
notional_value                                        0.0
trades_value                                 1883183000.0
trades_volume                                         303
trades_num                                             40
name                        اختيارخ اهرم-46000-1405/06/25
ticker                                           ضهرم6046
bid_price                                            6001
bid_volume                                            100
ask_price                                            6800
ask_volume                                             64
yesterday_open_positions                             2865
option_type                                          call
Name: 0, dtype: object

### Screen Market

In [3]:
from tseopt.use_case.screen_market import OptionMarket, convert_to_billion_toman

option_market = OptionMarket(entire_option_market_data=entire_option_market_data)

print(f"total_trade_value: {option_market.total_trade_value / 1e10:.0f} B Toman", end="\n\n")

most_trade_value_calls = pd.DataFrame(option_market.most_trade_value.get("call"))
most_trade_value_calls['ticker'] = most_trade_value_calls['ticker'].astype(str)
most_trade_value_calls["trades_value"] = convert_to_billion_toman(most_trade_value_calls["trades_value"])


most_trade_value_puts = pd.DataFrame(option_market.most_trade_value.get("put"))
most_trade_value_puts['ticker'] = most_trade_value_puts['ticker'].astype(str)
most_trade_value_puts["trades_value"] = convert_to_billion_toman(most_trade_value_puts["trades_value"])


most_trade_value_by_underlying_asset = pd.DataFrame(option_market.most_trade_value_by_underlying_asset)
most_trade_value_by_underlying_asset[["call", "put", "total"]] = convert_to_billion_toman(most_trade_value_by_underlying_asset[["call", "put", "total"]])


display(most_trade_value_calls)
display(most_trade_value_puts)
display(most_trade_value_by_underlying_asset)

total_trade_value: 1129 B Toman

     ticker    trades_value
0  ضهرم5035  136.43 B Toman
1  ضهرم4031   91.43 B Toman
2  ضهرم4030   50.91 B Toman
3  ضهرم4029   44.86 B Toman
4  ضهرم4028   35.89 B Toman

     ticker   trades_value
0  طهرم5033  44.66 B Toman
1  طهرم5032  30.72 B Toman
2  طهرم4031  25.47 B Toman
3  طهرم5034  21.31 B Toman
4  طهرم4032  15.73 B Toman

  ua_ticker           call             put           total
0      اهرم  573.7 B Toman  204.67 B Toman  778.37 B Toman
1     وبملت  88.02 B Toman    24.5 B Toman  112.52 B Toman
2     خودرو   91.2 B Toman   14.95 B Toman  106.15 B Toman
3      شستا  49.38 B Toman   20.08 B Toman   69.47 B Toman
4      شپنا  39.02 B Toman    0.03 B Toman   39.05 B Toman

### Options Chains

In [4]:
from tseopt.use_case.options_chains import Chains

chains = Chains(entire_option_market_data)

# Display underlying asset information to help select ua_tse_codes
print("Underlying Asset Information:")
print(chains.underlying_asset_info.head(5))

ua_tse_code = "17914401175772326" # اهرم

# Option types can be "call", "put", or "both"
options = chains.options(ua_tse_code=ua_tse_code, option_type="both")
date_chain = chains.make_date_chains(ua_tse_code=ua_tse_code, option_type="both") 
strike_price_chain = chains.make_strike_price_chains(ua_tse_code=ua_tse_code, option_type="call")
display(options)

# strike_price_chain and date_chain are generators.
# If you're not familiar with generators (and if you're wondering what the heck they are!), 
# uncomment the lines below to convert them to lists

# strike_price_chain = list(strike_price_chain)
# date_chain = list(date_chain)

Underlying Asset Information:
         ua_tse_code ua_ticker
0  17914401175772326      اهرم
1    778253364357513     وبملت
2  65883838195688438     خودرو
3   2400322364771558      شستا
4   7745894403636165      شپنا

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,42832,42832,44616,20260620,20260916,46000,65,...,303,40,اختيارخ اهرم-46000-1405/06/25,ضهرم6046,6001,100,6800,64,2865,call
12,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,38000,9,...,116646,2294,اختيارخ اهرم-38000-1405/04/31,ضهرم4030,4341,40,4560,95,242926,call
96,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,46000,9,...,329203,4404,اختيارخ اهرم-46000-1405/04/31,ضهرم4032,720,2708,730,120,278799,call
97,1000,17914401175772326,اهرم,42832,42832,44616,20260620,20260916,26000,65,...,433,67,اختيارخ اهرم-26000-1405/06/25,ضهرم6040,17900,26,19000,30,1812,call
108,1000,17914401175772326,اهرم,42832,42832,44616,20260608,20260819,34000,37,...,10570,861,اختيارخ اهرم-34000-1405/05/28,ضهرم5030,10350,36,10440,25,67437,call
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,50000,9,...,14290,529,اختيارف اهرم-50000-1405/04/31,طهرم4033,7750,5,7900,2,26689,put
1196,1000,17914401175772326,اهرم,42832,42832,44616,20260608,20260819,22000,37,...,2709,59,اختيارف اهرم-22000-1405/05/28,طهرم5025,60,90,75,945,21477,put
1224,1000,17914401175772326,اهرم,42832,42832,44616,20260608,20260819,46000,37,...,79184,3369,اختيارف اهرم-46000-1405/05/28,طهرم5033,5061,2,5100,162,132916,put
1239,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,26000,9,...,13363,125,اختيارف اهرم-26000-1405/04/31,طهرم4026,20,206,25,200,55941,put
1240,1000,17914401175772326,اهرم,42832,42832,44616,20260620,20260916,42000,65,...,0,0,اختيارف اهرم-42000-1405/06/25,طهرم6045,2220,2,4999,28,117,put

In [5]:
date_chain = list(date_chain)
first_chain = date_chain[0]

name = first_chain.loc[0, "name"]
jalali_date = name.split("-")[2]
print("Date: ", jalali_date)
display(first_chain.head(10))

Date:  1405/04/31

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,20000,9,...,1712,146,اختيارخ اهرم-20000-1405/04/31,ضهرم4023,21400,315,21950,15,98422,call
1,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,20000,9,...,32108,200,اختيارف اهرم-20000-1405/04/31,طهرم4023,13,1005,17,2073,180231,put
2,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,22000,9,...,9272,94,اختيارف اهرم-22000-1405/04/31,طهرم4024,15,1000,22,198,34984,put
3,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,22000,9,...,4072,130,اختيارخ اهرم-22000-1405/04/31,ضهرم4024,19501,47,19700,6,40890,call
4,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,24000,9,...,925,60,اختيارخ اهرم-24000-1405/04/31,ضهرم4025,17511,2,17782,85,59681,call
5,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,24000,9,...,19564,139,اختيارف اهرم-24000-1405/04/31,طهرم4025,18,1000,25,172,61607,put
6,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,26000,9,...,2245,120,اختيارخ اهرم-26000-1405/04/31,ضهرم4026,15511,49,15750,9,75520,call
7,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,26000,9,...,13363,125,اختيارف اهرم-26000-1405/04/31,طهرم4026,20,206,25,200,55941,put
8,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,28000,9,...,28454,170,اختيارف اهرم-28000-1405/04/31,طهرم4027,26,5000,33,500,86460,put
9,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,28000,9,...,8014,154,اختيارخ اهرم-28000-1405/04/31,ضهرم4027,13601,50,13780,29,116459,call

In [6]:
for idx, chain in enumerate(strike_price_chain):
    print("Strike Price: ", chain.loc[0, "strike_price"])
    display(chain)
    print("\n\n")
    if idx > 2:
        print("and ...")
        break

Strike Price:  20000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,20000,9,...,1712,146,اختيارخ اهرم-20000-1405/04/31,ضهرم4023,21400,315,21950,15,98422,call

Strike Price:  22000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,22000,9,...,4072,130,اختيارخ اهرم-22000-1405/04/31,ضهرم4024,19501,47,19700,6,40890,call
1,1000,17914401175772326,اهرم,42832,42832,44616,20260608,20260819,22000,37,...,753,92,اختيارخ اهرم-22000-1405/05/28,ضهرم5025,20800,22,22000,3,20660,call

Strike Price:  24000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,24000,9,...,925,60,اختيارخ اهرم-24000-1405/04/31,ضهرم4025,17511,2,17782,85,59681,call
1,1000,17914401175772326,اهرم,42832,42832,44616,20260608,20260819,24000,37,...,808,53,اختيارخ اهرم-24000-1405/05/28,ضهرم5026,13500,10,21000,5,2833,call

Strike Price:  26000

,contract_size,ua_tse_code,ua_ticker,ua_close_price,ua_last_price,ua_yesterday_price,begin_date,end_date,strike_price,days_to_maturity,...,trades_volume,trades_num,name,ticker,bid_price,bid_volume,ask_price,ask_volume,yesterday_open_positions,option_type
0,1000,17914401175772326,اهرم,42832,42832,44616,20260221,20260722,26000,9,...,2245,120,اختيارخ اهرم-26000-1405/04/31,ضهرم4026,15511,49,15750,9,75520,call
1,1000,17914401175772326,اهرم,42832,42832,44616,20260608,20260819,26000,37,...,574,57,اختيارخ اهرم-26000-1405/05/28,ضهرم5027,15130,1,18000,5,2580,call
2,1000,17914401175772326,اهرم,42832,42832,44616,20260620,20260916,26000,65,...,433,67,اختيارخ اهرم-26000-1405/06/25,ضهرم6040,17900,26,19000,30,1812,call

and ...

### Historical Order Book

In [ ]:
from tseopt import fetch_historical_lob

jalali_date = "1405-04-22"
tse_code = "65638031284142833" # ضهرم6047

all_lob = fetch_historical_lob(tse_code=tse_code, jalali_date=jalali_date)
display(all_lob)

,level,ask_number,ask_volume,ask_price,bid_price,bid_volume,bid_number,time
0,1,0,0,0.0,4056.0,5,1,06:01:27
1,2,0,0,0.0,2116.0,20,1,06:01:27
2,3,0,0,0.0,2001.0,1,1,06:01:27
3,4,0,0,0.0,51.0,22,1,06:01:27
4,5,0,0,0.0,22.0,47,2,06:01:27
...,...,...,...,...,...,...,...,...
841,1,1,5,5098.0,4602.0,11,1,13:45:07
842,2,1,95,5100.0,4559.0,69,1,13:45:07
843,3,1,1,5273.0,4555.0,4,1,13:45:07
844,4,1,5,7500.0,4551.0,1,1,13:45:07
845,5,1,12,7800.0,4503.0,100,1,13:45:07

In [10]:
from tseopt import take_lob_screenshot

specific_time = "10:50"
lob = take_lob_screenshot(entire_data=all_lob, specific_time=specific_time)
display(lob)

,level,ask_number,ask_volume,ask_price,bid_price,bid_volume,bid_number,time
0,1,1,1,4800.0,4555.0,20,1,10:48:18
1,2,1,10,4899.0,4551.0,11,2,10:48:18
2,3,2,106,4950.0,4550.0,33,1,10:47:12
3,4,1,20,5400.0,4502.0,100,1,10:47:12
4,5,1,1,5695.0,4501.0,79,2,10:47:12

### Tadbir API
Provides low latency and more detailed data (such as initial margin and order book). This may be suitable for obtaining data for actual trading.

In [13]:
from tseopt import tadbir_api

from pprint import pprint

isin_list = ["IRO9AHRM0C91", "IRO9AHRM0B21",]

bulk_data = tadbir_api.get_last_bulk_data(isin_list=isin_list)
detail_data = tadbir_api.get_detail_data(isin_list[0])
symbol_info = detail_data.get("symbol_info")
order_book = pd.DataFrame(detail_data.get("order_book"))

display(bulk_data)

pprint(symbol_info)
display(order_book)

,BasisVolume,ClosingPrice,CompanyName,BestBuyPrice,BestBuyQuantity,BestSellPrice,BestSellQuantity,NoBestBuy,NoBestSell,FirstTradedPrice,...,TotalTradeValue,TradeDate,varSign,ClosingPriceVar,ClosingPriceVarPercent,LastTradedPriceVar,LastTradedPriceVarPercent,tse_code,SectorCodeId,cs
0,1.0,4864.0,اختیارخ اهرم-50000-1405/06/25,4602.0,11,5098.0,5,1,1,4690.0,...,7.111114e+09,1405/4/22 12:29,1,326.0,7.18,452.0,9.96,65638031284142833,None,1000
1,1.0,18873.0,اختیارخ اهرم-24000-1405/05/28,13500.0,10,21000.0,5,1,1,17001.0,...,1.524900e+10,1405/4/22 12:29,0,911.0,5.07,1028.0,5.72,23368996807956154,None,1000

{'BaseVolume': 1,
 'CP12': 4864,
 'ClosingPrice': 4864.0,
 'CompanyTitle': 'اختیارخ اهرم-50000-1405/06/25',
 'GroupStateID': 8,
 'HighAllowedPrice': 500000.0,
 'HighPrice': 5222.0,
 'InstrumentCode': '65638031284142833',
 'IsCautionAgreement': False,
 'IsSepahAgreement': False,
 'LastTradedPrice': 4990.0,
 'LotSize': 1,
 'LowAllowedPrice': 1.0,
 'LowPercent': 100,
 'LowPrice': 4301.0,
 'MarketType': 'MarketType.BuyOption',
 'MaxPercent': 10918,
 'MaxQuantityOrder': 1000,
 'MinQuantityOrder': 1,
 'NSCCode': 'IRO9AHRM0C91',
 'RefPrice': 4538.0,
 'Symbol': 'ضهرم6047',
 'SymbolStateId': 1,
 'TickSize': 1.0,
 'TotalNumberOfSharesTraded': 1462,
 'TotalNumberOfTrades': 53,
 'TotalTradeValue': 7111114000.0,
 'TradeDate': '1405/04/22 - 12:29:44',
 'UA_LastTradedPrice': 42832.0,
 'UA_isin': 'IRT1AHRM0001',
 'YesterdayPrice': 4538.0,
 'contractSize': 1000,
 'contractStartDate': '1405/03/30',
 'cpv': 326.0,
 'cpvp': 7.18,
 'crn': 'ریال',
 'crp': 1,
 'exerciseDate': '1405/06/25',
 'gc': '3A',
 'initial_margin': 4290000.0,
 'iso': True,
 'lpv': 452.0,
 'lpvp': 9.96,
 'mbop': 0,
 'mcaop': 64000,
 'mcop': 64000,
 'mmop': 2750000,
 'openPositionNum': 6189,
 'pv': 9.96,
 'rm': 9154000.0,
 'strikePrice': 50000.0,
 'th': 535915.0,
 'tl': 0.0,
 'vs': 1}

,BestBuyPrice,BestSellPrice,BestSellQuantity,BestBuyQuantity,NoBestBuy,NoBestSell,NSCCode,Place
0,4602.0,5098.0,5,11,1,1,IRO9AHRM0C91,1
1,4559.0,5100.0,95,69,1,1,IRO9AHRM0C91,2
2,4555.0,5273.0,1,4,1,1,IRO9AHRM0C91,3
3,4551.0,7500.0,5,1,1,1,IRO9AHRM0C91,4
4,4503.0,7800.0,12,100,1,1,IRO9AHRM0C91,5

### Mercantile Exchange
Fetches all data which mercantile exchange website provides.

In [17]:
from tseopt import make_a_mercantile_data_object


md = make_a_mercantile_data_object()
md.update_data(timeout=20)
print(md.gavahi[0])
print(md.sandoq[0])
# print(md.salaf[0])
print(md.cdc[0])
print(md.all_market)
print(md.future_date_time)
# print(md.future[0])
print(md.markets_info[0])

{'InsCode': '57374840325378191', 'Symbol': 'زعف0510پ11', 'Code': 'IRK1A12205A1', 'Name': 'زعفران0510نگين سحرخيز(پ)', 'EnName': 'Zaferan 0510-122', 'Quantity': 131.0, 'Volume': 26832.0, 'Value': 71160217.377, 'FinalPrice': 2652065.0, 'LastPrice': 2631000.0, 'PriceChange': -40749.0, 'MinPrice': 2620000.0, 'MaxPrice': 2689999.0, 'FirstPrice': 2675102.0, 'YesterdayPrice': 2671749.0, 'DemandVolume1': 6, 'DemandQuantity1': 1, 'DemandPrice1': 2625105, 'OfferPrice1': 2631000, 'OfferQuantity1': 1, 'OfferVolume1': 29, 'DemandVolume2': 10, 'DemandQuantity2': 1, 'DemandPrice2': 2625101, 'OfferPrice2': 2631200, 'OfferQuantity2': 1, 'OfferVolume2': 1574, 'DemandVolume3': 10, 'DemandQuantity3': 1, 'DemandPrice3': 2625000, 'OfferPrice3': 2634000, 'OfferQuantity3': 1, 'OfferVolume3': 100, 'DemandVolume4': 15, 'DemandQuantity4': 1, 'DemandPrice4': 2620002, 'OfferPrice4': 2634999, 'OfferQuantity4': 1, 'OfferVolume4': 3, 'DemandVolume5': 10, 'DemandQuantity5': 1, 'DemandPrice5': 2612345, 'OfferPrice5': 2635000, 'OfferQuantity5': 1, 'OfferVolume5': 490, 'Time': '16:59:20', 'Status': 0, 'Buy_Count_ClientI': 37, 'Buy_Count_ClientN': 3, 'Buy_I_Volume': 16612.0, 'Buy_N_Volume': 10220.0, 'Sell_Count_ClientI': 41, 'Sell_Count_ClientN': 1, 'Sell_I_Volume': 25832.0, 'Sell_N_Volume': 1000.0, 'ModifyDate': '2026-07-13T00:00:00+03:30', 'ModifyTime': '17:01:16'}
{'InsCode': '34144395039913458', 'Symbol': 'عيار', 'Code': 'IRTKMOFD0001', 'Name': 'صندوق طلاي عيار مفيد', 'EnName': 'Ayar', 'Quantity': 32574.0, 'Volume': 27105172.0, 'Value': 13249976221.615, 'FinalPrice': 488836.0, 'LastPrice': 489430.0, 'PriceChange': -3966.0, 'MinPrice': 486991.0, 'MaxPrice': 490002.0, 'FirstPrice': 490000.0, 'YesterdayPrice': 493396.0, 'DemandVolume1': 789, 'DemandQuantity1': 2, 'DemandPrice1': 489430, 'OfferPrice1': 489431, 'OfferQuantity1': 8, 'OfferVolume1': 10146, 'DemandVolume2': 5000, 'DemandQuantity2': 1, 'DemandPrice2': 489420, 'OfferPrice2': 489447, 'OfferQuantity2': 1, 'OfferVolume2': 30, 'DemandVolume3': 7251, 'DemandQuantity3': 9, 'DemandPrice3': 489410, 'OfferPrice3': 489448, 'OfferQuantity3': 1, 'OfferVolume3': 30, 'DemandVolume4': 30, 'DemandQuantity4': 2, 'DemandPrice4': 489401, 'OfferPrice4': 489449, 'OfferQuantity4': 1, 'OfferVolume4': 15, 'DemandVolume5': 6425, 'DemandQuantity5': 24, 'DemandPrice5': 489400, 'OfferPrice5': 489450, 'OfferQuantity5': 4, 'OfferVolume5': 3103, 'Time': '16:59:59', 'Status': 0, 'Buy_Count_ClientI': 13184, 'Buy_Count_ClientN': 39, 'Buy_I_Volume': 25123532.0, 'Buy_N_Volume': 1981640.0, 'Sell_Count_ClientI': 7343, 'Sell_Count_ClientN': 30, 'Sell_I_Volume': 25717838.0, 'Sell_N_Volume': 1387334.0, 'ModifyDate': '2026-07-13T00:00:00+03:30', 'ModifyTime': '17:01:16'}
{'ContractID': 44, 'ContractCode': 'CopperCthd', 'ContractDescription': 'گواهی سپرده پیوسته مس کاتد', 'LastTradingPersianDate': '1410/12/01', 'ContractSize': 1.0, 'ContractSizeUnitFaDesc': 'ضریب تبدیل نماد به گروه انبار', 'TotalAssetChangesColor': 'Gray', 'ContractCurrencyFaDesc': 'ریال', 'LastSettlementPrice': 21448447.0, 'AskPrice1': None, 'AskVolume1': None, 'AskPrice2': None, 'AskVolume2': None, 'AskPrice3': None, 'AskVolume3': None, 'AskTotalVolume': None, 'BidPrice1': None, 'BidVolume1': None, 'BidPrice2': None, 'BidVolume2': None, 'BidPrice3': None, 'BidVolume3': None, 'BidTotalVolume': None, 'ContractCurrencyEnDesc': 'Rials', 'LastSettlementPricePersianDate': '1405/04/22', 'LastUpdate': '2026-07-13T17:31:44.54', 'HighTradedPriceChanges': None, 'HighTradedPrice': None, 'LastTradedPriceChangesColor': 'Gray', 'LastTradedPriceChangesVisibility': 'Collapsed', 'LastTradedPriceChangesPercent': None, 'LastTradedPriceChanges': None, 'LastTradedPriceTime': '', 'LastTradedPrice': None, 'FirstTradedPriceChangesColor': 'Gray', 'FirstTradedPriceChangesVisibility': 'Collapsed', 'FirstTradedPriceChangesPercent': None, 'FirstTradedPriceChanges': None, 'FirstTradedPriceTime': '', 'FirstTradedPrice': None, 'HighTradedPriceChangesPercent': None, 'HighTradedPriceChangesVisibility': 'Collapsed', 'HighTradedPriceChangesColor': 'Gray', 'LowTradedPrice': None, 'TotalAssetChangesVisibility': 'Visible', 'TotalAssetChangesPercent': 0.0, 'TotalAssetChanges': 0, 'TotalAsset': 2914864, 'TradesValueCurrencyEnDesc': '', 'TradesValueCurrencyFaDesc': '', 'OrderTimeVisibility': 'Collapsed', 'TradesValue': None, 'TradesVolume': None, 'TradesCount': None, 'LowTradedPriceChangesColor': 'Gray', 'LowTradedPriceChangesVisibility': 'Collapsed', 'LowTradedPriceChangesPercent': None, 'LowTradedPriceChanges': None, 'TradesVolumeVisibility': 'Collapsed', 'OrdersPersianDateTime': '17:00:21', 'OrdersDateTime': '2026-07-13T17:00:21.76', 'OrdersCounter': -1, 'CommodityID': 14, 'CommodityName': 'مس کاتد', 'CommodityColor': '#FFCF8A7A', 'CommodityColor1': '#FFDA8A68', 'TradesCounter': -1, 'IsOrdersHighLight': False, 'IsTradesHighLight': False}
{'id': 1, 'Description': 'تابلو آتی', 'TradeCount': 0, 'Buyers': 0, 'Sellers': 0, 'LegalBuyerCount': 0, 'NaturalBuyerCount': 0, 'LegalSellerCount': 0, 'NaturalSellerCount': 0}
None
{'ContractCode': 'SLSH05C400', 'CallContractID': 1002080, 'CallContractCode': 'SLSH05C400', 'CallContractDescription': 'قرارداد اختیار معامله خرید شمش نقره سررسید شهریور ماه 1405 با قیمت اعمال 4,000,000 ریال', 'CallLastTradingPersianDate': '1405/06/24', 'CallContractSize': 1.0, 'CallContractSizeUnitFaDesc': 'SilverBar', 'CallContractCurrencyFaDesc': 'ریال', 'CallContractCurrencyEnDesc': 'Rials', 'CallLastSettlementPrice': 289874.0, 'CallLastSettlementPricePersianDate': '1405/04/21', 'CallBidTotalVolume': None, 'CallBidVolume1': None, 'CallBidPrice1': None, 'CallBidVolume2': None, 'CallBidPrice2': None, 'CallBidVolume3': None, 'CallBidPrice3': None, 'CallBidVolume4': 0, 'CallBidPrice4': 0.0, 'CallBidVolume5': 0, 'CallBidPrice5': 0.0, 'CallAskTotalVolume': None, 'CallAskVolume1': None, 'CallAskPrice1': None, 'CallAskVolume2': None, 'CallAskPrice2': None, 'CallAskVolume3': None, 'CallAskPrice3': None, 'CallAskVolume4': 0, 'CallAskPrice4': 0.0, 'CallAskVolume5': 0, 'CallAskPrice5': 0.0, 'CallOrdersDateTime': '2026-07-13T17:01:21.867', 'CallOrdersPersianDateTime': '1405/04/22 - 17:01:21', 'CallOrderTimeVisibility': 'Collapsed', 'CallFirstTradedPrice': 250000.0, 'CallFirstTradedPriceTime': '15:10:56', 'CallFirstTradedPriceChanges': -39874.0, 'CallFirstTradedPriceChangesPercent': -13.760000228881836, 'CallFirstTradedPriceChangesVisibility': 'Visible', 'CallFirstTradedPriceChangesColor': 'Red', 'CallLastTradedPrice': 300000.0, 'CallLastTradedPriceTime': '16:26:43', 'CallLastTradedPriceChanges': 10126.0, 'CallLastTradedPriceChangesPercent': 3.490000009536743, 'CallLastTradedPriceChangesVisibility': 'Visible', 'CallLastTradedPriceChangesColor': 'Green', 'CallHighTradedPrice': 300000.0, 'CallHighTradedPriceChanges': 10126.0, 'CallHighTradedPriceChangesPercent': 3.490000009536743, 'CallHighTradedPriceChangesVisibility': 'Visible', 'CallHighTradedPriceChangesColor': 'Green', 'CallInitialMargin': 430000.0, 'CallRequiredMargin': 716578.0, 'CallLowTradedPrice': 250000.0, 'CallLowTradedPriceChanges': -39874.0, 'CallLowTradedPriceChangesPercent': -13.760000228881836, 'CallLowTradedPriceChangesVisibility': 'Visible', 'CallLowTradedPriceChangesColor': 'Red', 'CallTradesCount': 4, 'CallTradesVolume': 209, 'CallTradesVolumeVisibility': 'Visible', 'CallTradesValue': 52300.0, 'CallTradesValueCurrencyFaDesc': 'هزار ریال', 'CallTradesValueCurrencyEnDesc': 'Thousand Rials', 'CallOpenInterests': 170327, 'CallOpenInterestsChanges': 209, 'CallOpenInterestsChangesPercent': 0.11999999731779099, 'CallOpenInterestsChangesVisibility': 'Visible', 'CallOpenInterestsChangesColor': 'Green', 'CallIsOrdersHighLight': False, 'CallIsTradesHighLight': False, 'CallOrdersCounter': -1, 'CallTradesCounter': -1, 'PutContractID': 1002089, 'PutContractCode': 'SLSH05P400', 'PutContractDescription': 'قرارداد اختیار معامله فروش شمش نقره سررسید شهریور ماه 1405 با قیمت اعمال 4,000,000 ریال', 'PutLastTradingPersianDate': '1405/06/24', 'PutContractSize': 1.0, 'PutContractSizeUnitFaDesc': 'SilverBar', 'PutContractCurrencyFaDesc': 'ریال', 'PutContractCurrencyEnDesc': 'Rials', 'PutLastSettlementPrice': 473956.0, 'PutLastSettlementPricePersianDate': '1405/04/21', 'PutBidTotalVolume': None, 'PutBidVolume1': None, 'PutBidPrice1': None, 'PutBidVolume2': None, 'PutBidPrice2': None, 'PutBidVolume3': None, 'PutBidPrice3': None, 'PutBidVolume4': 0, 'PutBidPrice4': 0.0, 'PutBidVolume5': 0, 'PutBidPrice5': 0.0, 'PutAskTotalVolume': None, 'PutAskVolume1': None, 'PutAskPrice1': None, 'PutAskVolume2': None, 'PutAskPrice2': None, 'PutAskVolume3': None, 'PutAskPrice3': None, 'PutAskVolume4': 0, 'PutAskPrice4': 0.0, 'PutAskVolume5': 0, 'PutAskPrice5': 0.0, 'PutOrdersDateTime': None, 'PutOrdersPersianDateTime': '', 'PutOrderTimeVisibility': 'Collapsed', 'PutFirstTradedPrice': None, 'PutFirstTradedPriceTime': '', 'PutFirstTradedPriceChanges': None, 'PutFirstTradedPriceChangesPercent': None, 'PutFirstTradedPriceChangesVisibility': 'Collapsed', 'PutFirstTradedPriceChangesColor': 'Gray', 'PutLastTradedPrice': None, 'PutLastTradedPriceTime': '', 'PutLastTradedPriceChanges': None, 'PutLastTradedPriceChangesPercent': None, 'PutLastTradedPriceChangesVisibility': 'Collapsed', 'PutLastTradedPriceChangesColor': 'Gray', 'PutHighTradedPrice': None, 'PutHighTradedPriceChanges': None, 'PutHighTradedPriceChangesPercent': None, 'PutHighTradedPriceChangesVisibility': 'Collapsed', 'PutHighTradedPriceChangesColor': 'Gray', 'PutInitialMargin': 740000.0, 'PutRequiredMargin': 1211740.0, 'PutLowTradedPrice': None, 'PutLowTradedPriceChanges': None, 'PutLowTradedPriceChangesPercent': None, 'PutLowTradedPriceChangesVisibility': 'Collapsed', 'PutLowTradedPriceChangesColor': 'Gray', 'PutTradesCount': 0, 'PutTradesVolume': None, 'PutTradesVolumeVisibility': 'Collapsed', 'PutTradesValue': None, 'PutTradesValueCurrencyFaDesc': '', 'PutTradesValueCurrencyEnDesc': '', 'PutOpenInterests': None, 'PutOpenInterestsChanges': None, 'PutOpenInterestsChangesPercent': 0.0, 'PutOpenInterestsChangesVisibility': 'Collapsed', 'PutOpenInterestsChangesColor': 'Gray', 'PutIsOrdersHighLight': False, 'PutIsTradesHighLight': False, 'PutOrdersCounter': -1, 'PutTradesCounter': -1, 'StrikePrice': 4000000.0, 'StrikeLevel': 0, 'LastUpdate': '2026-07-13T17:01:21.867', 'PutContractVisibility': 'Visible', 'ContractCategory': 'SH05\t\t\tتاریخ سررسید: 1405/06/24', 'CommodityGroup': 'SilverBar', 'ContractSubGroup': 'SilverBarSH05'}

#### Gavahi

In [18]:
display(pd.DataFrame(md.gavahi).head(5))

,InsCode,Symbol,Code,Name,EnName,Quantity,Volume,Value,FinalPrice,LastPrice,...,Buy_Count_ClientI,Buy_Count_ClientN,Buy_I_Volume,Buy_N_Volume,Sell_Count_ClientI,Sell_Count_ClientN,Sell_I_Volume,Sell_N_Volume,ModifyDate,ModifyTime
0,57374840325378191,زعف0510پ11,IRK1A12205A1,زعفران0510نگين سحرخيز(پ),Zaferan 0510-122,131.0,26832.0,7.116022e+07,2652065.0,2631000.0,...,37,3,16612.0,10220.0,41,1,25832.0,1000.0,2026-07-13T00:00:00+03:30,17:01:16
1,48021799996852800,زعف0510پ26,IRK1A12305A1,زعفران0510نگين بديعي(پ),Zaferan 0510-123,49.0,18753.0,4.960278e+07,2645058.0,2630000.0,...,6,1,5886.0,12867.0,35,0,18753.0,0.0,2026-07-13T00:00:00+03:30,17:01:16
2,55294951106810711,زعف0510پ20,IRK1A12405A1,زعفران0510نگين وحدت جام(پ),Zaferan 0510-124,37.0,5216.0,1.307529e+07,2506765.0,2500011.0,...,18,0,5216.0,0.0,16,0,5216.0,0.0,2026-07-13T00:00:00+03:30,17:01:16
3,11531883067848241,زعف0510پ09,IRK1A12905A1,زعفران0510نگين نوين(پ),Zaferan 0510-129,8.0,3608.0,9.286220e+06,2573786.0,2550000.0,...,3,0,3608.0,0.0,5,0,3608.0,0.0,2026-07-13T00:00:00+03:30,17:01:16

#### Sandoq

In [19]:
display(pd.DataFrame(md.sandoq).head(5))

,InsCode,Symbol,Code,Name,EnName,Quantity,Volume,Value,FinalPrice,LastPrice,...,Buy_Count_ClientI,Buy_Count_ClientN,Buy_I_Volume,Buy_N_Volume,Sell_Count_ClientI,Sell_Count_ClientN,Sell_I_Volume,Sell_N_Volume,ModifyDate,ModifyTime
0,34144395039913458,عيار,IRTKMOFD0001,صندوق طلاي عيار مفيد,Ayar,32574.0,27105172.0,1.324998e+10,488836.0,489430.0,...,13184,39,25123532.0,1981640.0,7343,30,25717838.0,1387334.0,2026-07-13T00:00:00+03:30,17:01:16
1,14035144070182412,ريتون,IRTKRITO0001,صندوق س. كالاي پاسارگاد,Rithon,10462.0,314563907.0,5.310301e+09,16881.0,16858.0,...,819,27,32996803.0,281567104.0,503,29,93703117.0,220860790.0,2026-07-13T00:00:00+03:30,17:01:16
2,46700660505281786,طلا,IRTKLOTF0001,صندوق س. كالاي پارسيان,Tala,8366.0,2845883.0,3.557168e+09,1249935.0,1250599.0,...,3080,28,2330553.0,515330.0,1554,46,2206250.0,639633.0,2026-07-13T00:00:00+03:30,17:01:16
3,6362118829011821,ليان,IRTKLIAN0001,صندوق س.كالاي ديباي معيار,Liyan,2548.0,100216858.0,3.220310e+09,32133.0,32209.0,...,216,22,12169299.0,88047559.0,135,15,16128059.0,84088799.0,2026-07-13T00:00:00+03:30,17:01:16
4,12390706505809150,گوهر,IRTKKIAN0001,صندوق س.كالاي كيان,Gohar,3571.0,3429158.0,2.866749e+09,835992.0,837560.0,...,893,33,2899780.0,529378.0,644,28,1003460.0,2425698.0,2026-07-13T00:00:00+03:30,17:01:16

#### Salaf

In [19]:
display(pd.DataFrame(md.salaf).head(5))

,ID,Code,Symbol,Name,YesterdayPrice,FinalPrice,LastPrice,PriceChange,FirstPrice,MinPrice,...,Buy_CountI,Buy_CountN,Buy_I_Volume,Buy_N_Volume,Sell_CountI,Sell_CountN,Sell_I_Volume,Sell_N_Volume,ModifyDate,ModifyTime
0,63624670675689374,IRBKSNG304A0,عسنگ3,سلف استاندارد سنگ آهن مركزي,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
1,51040923156442869,IRBKAPAK0542,عپاكشو,سلف موازي گروه صنعتي پاكشو,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
2,1185549032856396,IRBKABAH03B0,عبهمن,سلف خودرووانت كارا تك كابين,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
3,40246708135920665,IRBKSNG404A8,عسنگ4,سلف موازي سنگ آهن,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25
4,39587043114049835,IRBKKAL30455,عكاله3,سلف شير فرادما كاله,0.0,0.0,0.0,0.0,0.0,0.0,...,0,0,0.0,0.0,0,0,0.0,0.0,0001-01-01T00:00:00,08:36:25

#### Future

In [20]:
display(pd.DataFrame(md.future).head(5))

,ContractID,LastTradingDate,ContractCode,ContractDescription,ContractSize,ContractSizeUnitFaDesc,ContractSizeUnitEnDesc,ContractCurrencyFaDesc,ContractCurrencyEnDesc,ContractCurrencyDecimalPlaces,...,LegalBuyerCount,LegalSellerCount,NaturalBuyerCount,NaturalSellerCount,TodayLiveSettlement,TradeCount,TradeVolume,PersianOrdersDateTime,PersianLastSettlementPriceDate,PesrsianLastTradingDate
0,284,2025-04-15T00:00:00,ETCFA04,قرارداد آتی صندوق طلای لوتوس تحویل فروردین ماه...,1000.0,واحد,-,ریال,Rials,None,...,0,0,0,0,0.0,0,0,None,None,None
1,285,2025-03-02T00:00:00,KBES03,قرارداد آتی صندوق طلای کهربا تحویل اسفند ماه 1...,1000.0,واحد,-,ریال,Rials,None,...,0,0,0,0,0.0,0,0,None,None,None
2,289,2025-02-17T00:00:00,GB29BA03,قرارداد آتی شمش طلای خام 995 تحویل بهمن ماه 1403,1.0,گرم,-,ریال,Rials,None,...,0,0,0,0,0.0,0,0,None,None,None
3,290,2025-06-17T00:00:00,KBKH04,قرارداد آتی صندوق طلای کهربا تحویل خرداد ماه 1...,1000.0,واحد,-,ریال,Rials,None,...,0,0,0,0,0.0,0,0,None,None,None
4,291,2025-07-15T00:00:00,ETCTR04,قرارداد آتی صندوق طلای لوتوس تحویل تیر ماه 1404,1000.0,واحد,-,ریال,Rials,None,...,0,0,0,0,0.0,0,0,None,None,None

#### CDC

In [20]:
display(pd.DataFrame(md.cdc).head(5))

,ContractID,ContractCode,ContractDescription,LastTradingPersianDate,ContractSize,ContractSizeUnitFaDesc,TotalAssetChangesColor,ContractCurrencyFaDesc,LastSettlementPrice,AskPrice1,...,OrdersPersianDateTime,OrdersDateTime,OrdersCounter,CommodityID,CommodityName,CommodityColor,CommodityColor1,TradesCounter,IsOrdersHighLight,IsTradesHighLight
0,44,CopperCthd,گواهی سپرده پیوسته مس کاتد,1410/12/01,1.0,ضریب تبدیل نماد به گروه انبار,Gray,ریال,2.144845e+07,None,...,17:00:21,2026-07-13T17:00:21.76,-1,14,مس کاتد,#FFCF8A7A,#FFDA8A68,-1,False,False
1,43,SilverBar,گواهی سپرده پیوسته شمش نقره 999.9,1410/12/01,1.0,ضریب تبدیل نماد به گروه انبار,Green,ریال,3.685692e+06,None,...,17:00:26,2026-07-13T17:00:26.07,-1,21,شمش نقره,#F0F0F0,#E3E3E3,-1,False,False
2,42,GoldCoin,گواهی سپرده پیوسته تمام سکه بهار آزادی طرح جدید,1410/12/01,1.0,ضریب تبدیل نماد به گروه انبار,Red,ریال,1.761669e+09,None,...,17:32:50,2026-07-13T17:32:50.647,-1,4,سکه طلا,#64ffffce,#ffefef15,-1,False,False
3,48,IronOrePlt,گواهی سپرده پیوسته گندله سنگ آهن,1410/12/01,1.0,ضریب تبدیل نماد به گروه انبار,Gray,ریال,9.693700e+04,None,...,16:59:41,2026-07-13T16:59:41.243,-1,28,گندله سنگ آهن,#FFFFFFFF,#9a9b9c,-1,False,False
4,41,GoldBar,گواهی سپرده پیوسته شمش طلای +995,1410/12/01,10.0,ضریب تبدیل نماد به گروه انبار,Green,ریال,2.343231e+07,None,...,16:59:59,2026-07-13T16:59:59.027,-1,2,شمش طلا,#fdf5e6,#fdf5e6,-1,False,False

#### markets_info

In [21]:
display(pd.DataFrame(md.markets_info).head(5))

,ContractCode,CallContractID,CallContractCode,CallContractDescription,CallLastTradingPersianDate,CallContractSize,CallContractSizeUnitFaDesc,CallContractCurrencyFaDesc,CallContractCurrencyEnDesc,CallLastSettlementPrice,...,PutIsTradesHighLight,PutOrdersCounter,PutTradesCounter,StrikePrice,StrikeLevel,LastUpdate,PutContractVisibility,ContractCategory,CommodityGroup,ContractSubGroup
0,SLSH05C400,1002080,SLSH05C400,قرارداد اختیار معامله خرید شمش نقره سررسید شهر...,1405/06/24,1.0,SilverBar,ریال,Rials,289874.0,...,False,-1,-1,4000000.0,0,2026-07-13T17:01:21.867,Visible,SH05\t\t\tتاریخ سررسید: 1405/06/24,SilverBar,SilverBarSH05